### ISSUE TITLE
Build script & nuspec

### ISSUE THREAD

**Issue by ZeroCoolGOS** [sassdawe/PSWinTerminal#2]
What are you using to generate your nuget package?

Also have you automated the publish of your nuget package to the gallery?

**Comment by sassdawe** [comment]
No automation, I cannot really set up a CI/CD pipeline because I need WT for run the pester tests, and for WT, I need Windows 10. Publishing is just one more command to execute.

The nuget package is actually just a manual download from the gallery. I just click new release here, and upload it with some comments and a new tag :)

If this were a more complex project, I'd probably set up some sort of automation.
